# Generated by Django 3.1.7 on 2021-03-13 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OidcAuthenticationRequest',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', models.CharField(max_length=256)),
                ('state', models.CharField(
                    default='state-is-unique', max_length=256, unique=True)),
                ('endpoint', models.URLField(blank=True, null=True)),
                ('issuer', models.CharField(blank=True, max_length=256, null=True)),
                ('issuer_id', models.CharField(
                    blank=True, max_length=256, null=True)),
                ('code_challenge', models.CharField(
                    blank=True, max_length=256, null=True)),
                ('code_challenge_method', models.CharField(
                    blank=True, max_length=256, null=True)),
                ('code_verifier', models.CharField(
                    blank=True, max_length=256, null=True)),
                ('authz_url', models.URLField(blank=True, null=True)),
                ('jwks', models.TextField(blank=True, null=True)),
                ('json', models.TextField(blank=True, null=True)),
                ('successful', models.BooleanField(default=False)),
                ('provider_configuration', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='OidcAuthenticationToken',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('id_token', models.TextField(blank=True, null=True)),
                ('scope', models.CharField(blank=True, max_length=256, null=True)),
                ('token_type', models.CharField(
                    blank=True, max_length=256, null=True)),
                ('expires_in', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('authz_request', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='spid_oidc_rp.oidcauthenticationrequest')),
            ],
        ),
    ]
