# Generated by Django 3.1.7 on 2021-03-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spid_oidc_rp', '0002_auto_20210314_0200'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oidcauthenticationrequest',
            old_name='json',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='oidcauthenticationrequest',
            old_name='jwks',
            new_name='provider_jwks',
        ),
    ]
