# Generated by Django 3.1.7 on 2021-03-16 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spid_oidc_rp', '0005_oidcauthenticationtoken_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcauthenticationtoken',
            name='logged_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
