# Generated by Django 3.1.1 on 2021-03-11 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtconnect_oidc_rp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcauthenticationrequest',
            name='code',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='oidcauthenticationrequest',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='oidcauthenticationrequest',
            name='state',
            field=models.CharField(default='state-is-unique', max_length=256, unique=True),
        ),
    ]
