# Generated by Django 3.1.1 on 2021-03-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtconnect_oidc_rp', '0003_oidcauthenticationrequest_issuer'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcauthenticationrequest',
            name='issuer_id',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
