# Generated by Django 3.1.1 on 2021-03-13 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtconnect_oidc_rp', '0005_auto_20210313_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcauthenticationrequest',
            name='code_challenge',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='oidcauthenticationrequest',
            name='code_challenge_method',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='oidcauthenticationrequest',
            name='code_verifier',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
