# Generated by Django 3.1.1 on 2021-03-13 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtconnect_oidc_rp', '0007_auto_20210313_1651'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcauthenticationrequest',
            name='successful',
            field=models.BooleanField(default=False),
        ),
    ]
