# Generated by Django 3.1.1 on 2021-03-13 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jwtconnect_oidc_rp', '0008_oidcauthenticationrequest_successful'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oidcauthenticationrequest',
            name='code',
        ),
        migrations.CreateModel(
            name='OidcAuthenticationToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=256, null=True)),
                ('access_token', models.TextField(blank=True, null=True)),
                ('id_token', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('authn_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jwtconnect_oidc_rp.oidcauthenticationrequest')),
            ],
        ),
    ]
