# Generated by Django 3.1.1 on 2021-03-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jwtconnect_oidc_rp', '0009_auto_20210313_1718'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oidcauthenticationtoken',
            old_name='authn_request',
            new_name='authz_request',
        ),
    ]
