# Generated by Django 3.1.1 on 2021-03-13 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jwtconnect_oidc_rp', '0010_auto_20210313_1759'),
    ]

    operations = [
        migrations.AddField(
            model_name='oidcauthenticationtoken',
            name='expires_in',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='oidcauthenticationtoken',
            name='scope',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='oidcauthenticationtoken',
            name='token_type',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
